config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  namespace :admin do
   root 'application#index'
   resources :users, only: [:new, :create, :edit, :index]
   resources :books, only: [:new, :create, :destroy, :edit]
  end
  
  

  namespace :admin do
   get 'user/new'
  end
 
  
  
  
  
  resources :users, only: [:show]
  resources :books, only: [:index, :show]
  root 'static_pages#welcome'
  
  

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  
  def index
  end
  
  private
  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/index.html.erb
<div class="row" id="admin">
<div class="col-md-9">
<header>
<h1>Admin Lounge</h1>
</header>
<p>Welcome to Libraree's Admin Lounge. Please enjoy your stay.</p>
</div>
<div class="col-md-3">
<h2>Admin Links</h2>
        <ul class="nav nav-stacked">
          <li><%= link_to "Users", admin_users_path %></li>
          
        </ul>

  </div>
</div>