config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  namespace :admin do
   root 'application#index'
   resources :users, only: [:new, :create, :edit, :index]
   resources :books, only: [:new, :create, :destroy, :edit]
  end
  
  

  namespace :admin do
   get 'user/new'
  end
 
  
  
  
  
  resources :users, only: [:show]
  resources :books, only: [:index, :show]
  root 'static_pages#welcome'
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
<div class="collapse navbar-collapse" id="collapse">
<ul class="nav navbar-nav">
  <li class="<%= "active" if current_page?("/") %>">
<%= link_to "Home", root_path, class: "navbar-brand" %>
</li>
<li class="<%= "active" if current_page?("/books") %>">
<%= link_to "Books", books_path, class: "navbar-brand"%>
</li>
<% if current_user.try(:admin?) %>
    <li class="<%= "active" if current_page?("/admin") %>">
      <%= link_to "Admin", admin_root_path, class: "navbar-brand"%>
    </li>
    <%end%>
</ul>

 

  <% unless user_signed_in? %>
<div class="navbar-right">
  <ul class="nav navbar-nav">
    <li class="<%= "active" if current_page?("/users/sign_in") %>">
              <%= link_to "Sign in", new_user_session_path
                %>
                </li>
</ul>
           
</div>
 <% end %>
<% if user_signed_in? %>
          <div class="navbar-right">
            <p class="navbar-text">
              Signed in as <%= current_user.email %>
</p> 


             <ul class="nav navbar-nav">
              <li><%= link_to "Sign out", destroy_user_session_path,
                method: :delete %>
</li> </ul>
</div>
<% end %>
</div>
</nav>



<%= yield %>

</body>
</html>